splash=false
wallpaper {
    monitor = DP-1
    path = ~/.wallpapers/gruvbox/horizontal/minimalistic/gruv-understand.png
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = ~/.wallpapers/gruvbox/horizontal/mix/gruvbox15.png
    fit_mode = cover
}
