{ config, pkgs, ... }:
{
  # Import hardware config (generated by nixos-generate-config)
  # and all sub-modules from the modules/ directory
  imports = [
    ./hardware-configuration.nix
    ./modules
  ];

  # Host identity
  networking.hostName = "overrig";

  # NixOS 25.11 (unstable) state version
  system.stateVersion = "26.05";

  # Enable flakes and the new nix command interface
  nix.settings.experimental-features = [ "nix-command" "flakes" ];

  nixpkgs.config.allowUnfree = true;
  # Custom package overlays
  # Brave-Origin overlay disabled (build issues)
  # nixpkgs.overlays = [ (import ./overlay.nix) ];
}
